-- =============================================================================
-- SUPABASE SCHEMA - Real Estate Site v1
-- =============================================================================
-- Run this script in Supabase SQL Editor to create the properties table
-- =============================================================================

-- Drop table if exists (for development only, remove in production)
-- DROP TABLE IF EXISTS properties;

-- =============================================================================
-- PROPERTIES TABLE
-- =============================================================================

CREATE TABLE IF NOT EXISTS properties (
  -- Primary Key
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- URL-friendly identifier (unique)
  slug VARCHAR(255) NOT NULL UNIQUE,

  -- Basic info
  title VARCHAR(500) NOT NULL,
  category VARCHAR(20) NOT NULL CHECK (category IN ('sale', 'rent')),
  type VARCHAR(50) NOT NULL CHECK (type IN (
    'apartment', 'house', 'land',
    'ednostaen', 'destaen', 'tristaen', 'chetiristaen', 'mezonet', 'mezonet_ofis',
    'atelie', 'tavan', 'mnogostaen_penthaus', 'etaj_kashta', 'kashta', 'vila',
    'magazin', 'zavedenie', 'sklad', 'garaj', 'parkomqsto', 'promishleno',
    'hotel', 'parcel', 'zemedelska_zemya'
  )),
  status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'pending', 'sold', 'rented', 'inactive')),

  -- Price
  price DECIMAL(12, 2) NOT NULL CHECK (price >= 0),
  currency VARCHAR(3) NOT NULL DEFAULT 'EUR' CHECK (currency IN ('EUR', 'BGN')),

  -- Property details
  area DECIMAL(10, 2) NOT NULL CHECK (area > 0),
  rooms SMALLINT CHECK (rooms > 0),
  floor SMALLINT CHECK (floor >= 0),
  total_floors SMALLINT CHECK (total_floors > 0),
  year_built SMALLINT CHECK (year_built >= 1800 AND year_built <= 2100),

  -- Location
  city VARCHAR(100) NOT NULL,
  neighborhood VARCHAR(100),
  address VARCHAR(500) NOT NULL,

  -- Description & Features
  description TEXT NOT NULL,
  features TEXT[] NOT NULL DEFAULT '{}',
  images TEXT[] NOT NULL DEFAULT '{}',

  -- Map
  map_url TEXT,

  -- Flags
  is_featured BOOLEAN NOT NULL DEFAULT FALSE,

  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- INDEXES
-- =============================================================================

-- Unique index on slug (already created by UNIQUE constraint)
-- CREATE UNIQUE INDEX idx_properties_slug ON properties(slug);

-- Category index (sale/rent filtering)
CREATE INDEX idx_properties_category ON properties(category);

-- Type index (apartment/house/land filtering)
CREATE INDEX idx_properties_type ON properties(type);

-- Status index (active properties)
CREATE INDEX idx_properties_status ON properties(status);

-- City index (location filtering)
CREATE INDEX idx_properties_city ON properties(city);

-- Featured index (homepage featured properties)
CREATE INDEX idx_properties_featured ON properties(is_featured) WHERE is_featured = TRUE;

-- Composite index for common query pattern
CREATE INDEX idx_properties_category_status ON properties(category, status);

-- Created at index (sorting by date)
CREATE INDEX idx_properties_created_at ON properties(created_at DESC);

-- =============================================================================
-- TRIGGER: Auto-update updated_at timestamp
-- =============================================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_properties_updated_at
  BEFORE UPDATE ON properties
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- =============================================================================
-- ROW LEVEL SECURITY (RLS)
-- =============================================================================

-- Enable RLS
ALTER TABLE properties ENABLE ROW LEVEL SECURITY;

-- Policy: Anyone can read active properties (public access)
CREATE POLICY "Public can view active properties"
  ON properties
  FOR SELECT
  USING (status = 'active');

-- Policy: Authenticated users can view all properties (for admin)
CREATE POLICY "Authenticated users can view all properties"
  ON properties
  FOR SELECT
  TO authenticated
  USING (TRUE);

-- Policy: Authenticated users can insert properties (for admin)
CREATE POLICY "Authenticated users can insert properties"
  ON properties
  FOR INSERT
  TO authenticated
  WITH CHECK (TRUE);

-- Policy: Authenticated users can update properties (for admin)
CREATE POLICY "Authenticated users can update properties"
  ON properties
  FOR UPDATE
  TO authenticated
  USING (TRUE)
  WITH CHECK (TRUE);

-- Policy: Authenticated users can delete properties (for admin)
CREATE POLICY "Authenticated users can delete properties"
  ON properties
  FOR DELETE
  TO authenticated
  USING (TRUE);

-- =============================================================================
-- COMMENTS (Documentation)
-- =============================================================================

COMMENT ON TABLE properties IS 'Real estate listings for sale and rent';
COMMENT ON COLUMN properties.slug IS 'URL-friendly unique identifier';
COMMENT ON COLUMN properties.category IS 'sale or rent';
COMMENT ON COLUMN properties.type IS 'apartment, house, or land';
COMMENT ON COLUMN properties.status IS 'active, pending, sold, rented, or inactive';
COMMENT ON COLUMN properties.features IS 'Array of amenities/features';
COMMENT ON COLUMN properties.images IS 'Array of image URLs';
COMMENT ON COLUMN properties.map_url IS 'Google Maps URL';
COMMENT ON COLUMN properties.is_featured IS 'Show on homepage featured section';
